### ISSUE TITLE
App Browser/Back Button in Quick ID

### ISSUE THREAD

**Issue by muxe** [aeternity/aepp-identity#49]
on mobile screens the back button overlaps the quick id. in recent designs the back button is part of of the quick id.

is:
![screenshot from 2018-02-13 10-52-41](https://user-images.githubusercontent.com/356123/36156881-b2cc7380-10d8-11e8-99fe-963a0abb2a50.png)
should:
![screenshot from 2018-02-13 16-01-15](https://user-images.githubusercontent.com/356123/36156880-b2aed988-10d8-11e8-94f1-a2d741e22eb9.png)

**Comment by Philip-Nunoo** [comment]
progress to continue after this update.
