### ISSUE TITLE
onboarding looks strange on desktop

### ISSUE THREAD

**Issue by muxe** [aeternity/aepp-identity#69]
http://stage-identity.aepps.com/#/onboarding

content should be centered and probably width limited
![screenshot from 2018-03-01 17-43-49](https://user-images.githubusercontent.com/356123/36857178-279ea18c-1d78-11e8-8aff-8fa1610b7ecb.png)

**Comment by acdbaykal** [comment]
Hey @raymundjacobs, is muxe's assumption, that there should be a limit to the contents width correct? If yes, at what length?

**Comment by raymundjacobs** [comment]
@acdbaykal let's implement a max-width of 650px. Can we also limit the amount of blocks in the background to 9? I find it a bit too much

**Comment by acdbaykal** [comment]
@raymundjacobs, the cubes have a length of 72px. Therefore limiting the width to 650px should already do the trick.

**Comment by acdbaykal** [comment]
Fixed with #79 and #84
