### ISSUE TITLE
Question: Do Events work?

### ISSUE THREAD

**Issue by dadaphl** [aeternity/aepp-identity#94]
https://github.com/ethereum/wiki/wiki/JavaScript-API#contract-events

I registered a contract event in my aepp. Works in MetaMask but not in ID-Manager. The callback is just never called. Is that maybe a Infura Issue?

**Comment by muxe** [comment]
* probably an infura issue
* I'll look at it again

**Comment by muxe** [comment]
looks like you need a websocket connection to the node, which the IDM od id.manager-provider does not provide
